;;; cmake-clangd.el --- Setup clangd settings for cmake projects  -*- lexical-binding: t; -*-

;; Copyright (C) 2024 Thiago Pacheco Rocha

;; Author: Thiago Pacheco Rocha <thiagopachecorocha@hotmail.com>
;; Created: 06 Jan 2024
;; Version: 0.0.1

;; Keywords: tools
;; URL: https://example.com

;; Package-Requires: (eglot json)

;; This file is not part of GNU Emacs.

;;; Commentary:
;; Package that uses CMake's file API to correctly configure clangd LSP server.
;; It also adds functions to easily compile and run a CMake project.

;;; Code:

(require 'json)
(require 'eglot)

(defgroup cmake-clangd nil
  "Configure clangd to work with CMake."
  :prefix "cmake-clangd-"
  :group 'applications)

(defconst cmake-clangd-output-buffer "*cmake-clangd-output*"
  "The name of the buffer where output will be outputted.
It should be a read-only buffer.")

(defcustom cmake-clangd-build-dir "out/"
  "Directory where build files will be.
This is the directory used with \"-B\" cmake flag when configuring the project."
  :type 'directory
  :group 'cmake-clangd)

;;;;###autoload
(defun cmake-clangd-setup ()
  "Configures clangd to use compile_commands.json generated by CMake."
  (interactive)

  (let* ((eglot-project-root (expand-file-name (project-root (eglot--current-project))))
         (cmake-project-root (if (file-exists-p (concat eglot-project-root "CMakeLists.txt"))
                                 eglot-project-root
                               (unless (null buffer-file-name)
                                 (cmake-clangd-find-file-up-dir "CMakeLists.txt" (file-name-parent-directory buffer-file-name))))))
    (cmake-clangd-log "Eglot project: " eglot-project-root)
    (unless (null cmake-project-root)
      (cmake-clangd-log "Found an initial CMakeLists.txt in " cmake-project-root))

    (when (interactive-p)
      (setq cmake-project-root
            (expand-file-name (file-name-parent-directory
                               (read-file-name "Top-level CMakeLists.txt: " cmake-project-root "CMakeLists.txt" t "CMakeLists.txt"
                                               (lambda (file) (and
                                                               (file-exists-p file)
                                                               (string-match-p "CMakeLists\\.txt" file)))))))
      (cmake-clangd-log "User chose project root as: " cmake-project-root))

    (when (null cmake-project-root)
      (error "CMakeLists.txt not found"))

    (cmake-clangd-configure cmake-project-root)

    ;; Find executable targets with CMake file API
    ;; (let ((inhibit-read-only t)
    ;;       (cmake-api-dir (concat eglot-project-root cmake-clangd-build-dir
    ;;                              ".cmake/api/v1/"))
    ;;       (cmake-api-index nil))
    ;;   (make-empty-file (concat cmake-api-dir "query/codemodel-v2") t)
    ;;   (call-process "cmake" nil cmake-clangd-output-buffer nil
    ;;                 "-S" cmake-project-root
    ;;                 "-B" (concat eglot-project-root cmake-clangd-build-dir)
    ;;                 "-DCMAKE_BUILD_TYPE=Debug")
    ;;   (setq cmake-api-index
    ;;         (car-safe (directory-files (concat cmake-api-dir "reply/") t
    ;;                                    "index-.*\\.json")))
    ;;   (cmake-clangd-log "API index: " cmake-api-index)
    ;;   )
    )
  )

(defun cmake-clangd-configure (cmake-project-root)
  (let ((presets-file (concat cmake-project-root "CMakePresets.json")))
    (when (file-exists-p presets-file)
      (cmake-clangd-log "Presets found!")
      ;; Parse json (follow preset hierarchy)
      (let* ((presets-json (json-read-file "CMakePresets.json"))
             (configure-presets (alist-get 'configurePresets presets-json))
             (configure-presets-names
              (remove nil (mapcar (lambda (preset)
                                    (unless (alist-get 'hidden preset)
                                      (alist-get 'name preset)))
                                  configure-presets)))
             (chosen-preset (completing-read "Configure preset: " configure-presets-names nil t)))
        (cmake-clangd-log "Chosen preset: " chosen-preset)
        )
      ))
  )

(defun cmake-clangd-find-file-up-dir (filename directory)
  "Starting from `directory', tries to find `filename' file; if not found, goes
up 1 level in the directory hierarchy and repeat.
Returns the directory where `filename' is located, or nil if it is not found."
  (let ((cmake-project-root directory))
    (while (and (not (null cmake-project-root))
                (not (file-readable-p (concat cmake-project-root filename))))
      (setq cmake-project-root (file-name-parent-directory cmake-project-root)))

    cmake-project-root
    )
  )

(defun cmake-clangd-log (&rest strings)
  "Append `strings' to `cmake-clangd-output-buffer'."
  (with-current-buffer (get-buffer-create cmake-clangd-output-buffer)
    (read-only-mode t)
    (end-of-buffer)
    (let ((inhibit-read-only t))
      (apply 'insert strings)
      (insert "\n"))
    )
  )

;;; cmake-clangd.el ends here
