;;; cmake-clangd.el --- Setup clangd settings for cmake projects  -*- lexical-binding: t; -*-

;; Copyright (C) 2024 Thiago Pacheco Rocha

;; Author: Thiago Pacheco Rocha <thiagopachecorocha@hotmail.com>
;; Created: 06 Jan 2024
;; Version: 0.0.1

;; Keywords: tools
;; URL: https://example.com

;; Package-Requires: (eglot)

;; This file is not part of GNU Emacs.

;;; Commentary:
;; Package that uses CMake's file API to correctly configure clangd LSP server.
;; It also adds functions to easily compile and run a CMake project.

;;; Code:

(require 'json)
(require 'eglot)

;;;;###autoload
(defun cmake-clangd-setup ()
  "Configures clangd to use compile_commands.json generated by CMake."
  (interactive)

  (let* ((eglot-project (expand-file-name (project-root (eglot--current-project))))
        (opened-file (file-name-as-directory buffer-file-name))
        (cmake-project-root (if (file-exists-p (concat eglot-project "CMakeLists.txt"))
                                eglot-project
                              (cmake-clangd-find-file-up-dir "CMakeLists.txt" (file-name-parent-directory opened-file)))))

    (if (null cmake-project-root)
        (error "CMakeLists.txt not found")
      (message "Found an initial CMakeLists.txt in %s" cmake-project-root))

    (message "Eglot project: %s" eglot-project)
    )
  )

(defun cmake-clangd-find-file-up-dir (filename directory)
  "Starting from `directory', tries to find `filename' file; if not found, goes
up 1 level in the directory hierarchy and repeat.
Returns the directory where `filename' is located, or nil if it is not found."
  (let ((cmake-project-root directory))
    ;; Go up 1 directory until a CMakeLists.txt is found.
    (while (and (not (null cmake-project-root))
                (not (file-readable-p (concat cmake-project-root filename))))
      (setq cmake-project-root (file-name-parent-directory cmake-project-root)))

    cmake-project-root
    )
  )

;;; cmake-clangd.el ends here
